export const screens = {
  SplashScreen: 'SplashScreen',
  OnboardingScreen: 'OnboardingScreen',
  LoginScreen: 'LoginScreen',
  ForgotPasswordScreen: 'ForgotPasswordScreen',
  ResetPasswordScreen: 'ResetPasswordScreen',
  FitnessInfoScreen: 'FitnessInfoScreen',
  EditProfileScreen: 'EditProfileScreen',
  ChangePasswordScreen: 'ChangePasswordScreen',
  PurchaseHistoryScreen: 'PurchaseHistoryScreen',
  FilterScreen: 'FilterScreen',
  OrderDetailScreen: 'OrderDetailScreen',
  TermsScreen: 'TermsScreen',
  MainTabs: 'MainTabs',
  BreakfastDetailScreen: 'BreakfastDetailScreen',
  AddMealScreen: 'AddMealScreen',
  SearchFoodScreen: 'SearchFoodScreen',
  AddFitnessInfo: 'AddFitnessInfo',
  NutritionTargetScreen: 'NutritionTargetScreen',
  ChallengesScreen: 'ChallengesScreen',
};
